### PR TITLE
Kill2

### PR DESCRIPTION
**Pull request by fractal161**
well this was simpler than i expected lol. good design ig :P.

the option sets the line count where double killscreen kicks in. might benefit from a sound effect, but none has been added for now

### CODE REVIEW

**Comment by fractal161** [comment]
mmm another thing to consider would be if we'd want a way to show the config for the mode during topout so we can trust screenshot claims? not like anyone gets more than 10 lines but who knows

**Comment by kirjavascript** [comment]
nice one!

this would be find to merge as-is, but I had some thoughts;

* should we move killscreenx2 to with the other options so it looks nicer?
* will anyone want more than 10 lines ever? should we just have `0` and `1` and save the other numbers for other double killscreen types?
* level up sfx would be good but idc really it's not important
* is transition possible now? can you get to level 30 on double killscreen mode? might make a nice easter egg

**Comment by fractal161** [comment]
ok i think this is everything (i'll leave the menu shuffling to you since i'm kind of scared about breaking things lol)

**Review by kirjavascript — APPROVED** [review]

**Comment by kirjavascript** [comment]
looks good to me!

**Pull request merged**
